services:
  postgres:
    container_name: bcrd_postgres
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGPORT: 55432
      TZ: ${LOCATION_NAME}
      LANG: "ja_JP.UTF-8"
    build:
      context: .
      dockerfile: "./docker/postgres/Dockerfile"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "./db/postgres/data:/var/lib/postgresql/data"
      - "./docker/postgres/init:/docker-entrypoint-initdb.d"
      - "./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf"
    ports:
      - "55432:55432"
  api:
    container_name: bcrd_api
    environment:
      TZ: ${LOCATION_NAME}
    build:
      context: .
      dockerfile: "./docker/api/Dockerfile"
    volumes:
      - ./:/go/src/app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "50052:50052"