version: "3.9"
services:
  db:
    image: mysql:8.4.3
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: egp
      MYSQL_USER: egp_user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - "3306:3306"
  api:
    container_name: api
    build: .
    volumes:
      - ./:/go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
