version: "3.9"
services:
  postgres:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    container_name: postgres
    environment:
      POSTGRES_DB: egp
      POSTGRES_USER: egp_user
      POSTGRES_PASSWORD: password
      TZ: 'Asia/Tokyo'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U egp_user" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  api:
    container_name: api
    environment:
      TZ: Asia/Tokyo
    build: .
    volumes:
      - ./:/go/src/app
      - ../egp_protobuf:/go/src/egp_protobuf
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
