services:
  postgres:
    platform: linux/amd64
    restart: always
  api:
    platform: linux/amd64
    build:
      target: production
    restart: always
  nginx:
    image: nginx:1.28
    platform: linux/amd64
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    links:
      - "api"