services:
  postgres:
    platform: linux/amd64
    ports:
      - "5432:5432"
  api:
    platform: linux/amd64
    build:
      target: local
    ports:
      - "50051:50051"
  nginx:
    image: nginx:1.28
    platform: linux/amd64
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    links:
      - "api"
  pgadmin4:
    image: dpage/pgadmin4:8.4
    platform: linux/amd64
    container_name: pgadmin4
    ports:
      - "8888:80"
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: egp@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "True"
    depends_on:
      postgres:
        condition: service_healthy
